# This is a basic workflow to help you get started with Actions

name: staging

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    env:
      GIT_CRYPT_CMD: /usr/local/bin/git-crypt
      NODE_ENV: staging
      GIT_CRYPT_KEY: /home/travis/litentry-registrar-git-crypt-key-default
      TARGET_DIR: /home/travis/litentry-registrar/litentry-registrar
    # The type of runner that the job will run on
    runs-on: [self-hosted, litentry]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: deploy
        run: |
          $GIT_CRYPT_CMD unlock $GIT_CRYPT_KEY
          echo NODE_ENV=$NODE_ENV > $TARGET_DIR/.env
          yarn
          yarn run build
          [[ $(pm2 list 0 | grep online | wc -l) -ne 0 ]] && pm2 stop 0
          yarn start &> /dev/null
          sleep 5
          yarn run setup
          yarn test
